name: icon_maker
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  barcode_widget: ^2.0.4
  dfc_flutter:
    git: https://github.com/sgehrman/dfc_flutter
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  image: ^4.5.2
  jovial_svg: ^1.1.24

dev_dependencies:
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/rei-codes/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/screenshots/
    - assets/wallpaper/

  shaders:
    # - shaders/pyramid.glsl
    # - shaders/warp.glsl
    # - shaders/triangles.glsl
    # - shaders/nebula.glsl
    # - shaders/dmt.glsl
    # - shaders/boreal.glsl
    - shaders/coloredCells.glsl
    # - shaders/hyperboloid.glsl
    - shaders/starTunnel.glsl
    # - shaders/starfield.glsl
